<?php

namespace Database\Seeders;

use App\Models\System\Country;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table((new Country())->getTable())
          ->insert([
              [
                  'name'=>'United States',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/us.svg'
              ],
              [
                  'name'=>'Italy',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/it.svg'
              ],
              [
                  'name'=>'Austria',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/at.svg'
              ],
              [
                  'name'=>'Netherlands',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/nl.svg'
              ],
              [
                  'name'=>'Germany',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/de.svg'
              ],
              [
                  'name'=>'Belgium',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/be.svg'
              ],
              [
                  'name'=>'Poland',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/pl.svg'
              ],
              [
                  'name'=>'France',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/fr.svg'
              ],
              [
                  'name'=>'United Kingdom',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/gb.svg'
              ],
              [
                  'name'=>'Spain',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/es.svg'
              ],
              [
                  'name'=>'Canada',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/ca.svg'
              ],
              [
                  'name'=>'United Arab Emirates',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/ae.svg'
              ],
              [
                  'name'=>'Saudi Arabia',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/sa.svg'
              ],
              [
                  'name'=>'Japan',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/jp.svg'
              ],
              [
                  'name'=>'Finland',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/fi.svg'
              ],
              [
                  'name'=>'Portugal',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/pt.svg'
              ],
              [
                  'name'=>'Ireland',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/ie.svg'
              ],
              [
                  'name'=>'Afghanistan',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/af.svg'
              ],
              [
                  'name'=>'Albania',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/al.svg'
              ],
              [
                  'name'=>'Algeria',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/dz.svg'
              ],
              [
                  'name'=>'American Samoa',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/as.svg'
              ],
              [
                  'name'=>'Angola',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/ao.svg'
              ],
              [
                  'name'=>'Anguilla',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/ai.svg'
              ],
              [
                  'name'=>'Antigua and Barbuda',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/ag.svg'
              ],
              [
                  'name'=>'Argentina',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/ar.svg'
              ],
              [
                  'name'=>'Armenia',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/am.svg'
              ],
              [
                  'name'=>'Aruba',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/aw.svg'
              ],
              [
                  'name'=>'Australia',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/au.svg'
              ],
              [
                  'name'=>'Bahamas',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/bs.svg'
              ],
              [
                  'name'=>'Bahrain',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/bh.svg'
              ],
              [
                  'name'=>'Bangladesh',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/bd.svg'
              ],
              [
                  'name'=>'Barbados',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/bb.svg'
              ],
              [
                  'name'=>'Belarus',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/by.svg'
              ],
              [
                  'name'=>'Belize',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/bz.svg'
              ],
              [
                  'name'=>'Benin',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/bj.svg'
              ],
              [
                  'name'=>'Bermuda',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/bm.svg'
              ],
              [
                  'name'=>'Bolivia',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/bo.svg'
              ],
              [
                  'name'=>'Botswana',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/bw.svg'
              ],
              [
                  'name'=>'Brazil',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/br.svg'
              ],
              [
                  'name'=>'Burkina Faso',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/bf.svg'
              ],
              [
                  'name'=>'Burundi',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/bi.svg'
              ],
              [
                  'name'=>'Cambodia',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/kh.svg'
              ],
              [
                  'name'=>'Cameroon',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/cm.svg'
              ],
              [
                  'name'=>'Cape Verde',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/cv.svg'
              ],
              [
                  'name'=>'Cayman Islands',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/ky.svg'
              ],
              [
                  'name'=>'Central African Republic',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/cf.svg'
              ],
              [
                  'name'=>'Chile',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/cl.svg'
              ],
              [
                  'name'=>'China',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/cn.svg'
              ],
              [
                  'name'=>'Colombia',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/co.svg'
              ],
              [
                  'name'=>'Comoros',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/km.svg'
              ],
              [
                  'name'=>'Congo',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/cg.svg'
              ],
              [
                  'name'=>'The Democratic Republic Of Congo',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/cd.svg'
              ],
              [
                  'name'=>'Costa Rica',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/cr.svg'
              ],
              [
                  'name'=>'Côte d\'Ivoire',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/ci.svg'
              ],
              [
                  'name'=>'Cuba',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/cu.svg'
              ],
              [
                  'name'=>'Cyprus',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/cy.svg'
              ],
              [
                  'name'=>'Dominica',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/dm.svg'
              ],
              [
                  'name'=>'Dominican Republic',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/do.svg'
              ],
              [
                  'name'=>'Ecuador',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/ec.svg'
              ],
              [
                  'name'=>'Egypt',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/eg.svg'
              ],
              [
                  'name'=>'El Salvador',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/sv.svg'
              ],
              [
                  'name'=>'Ethiopia',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/et.svg'
              ],
              [
                  'name'=>'Fiji',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/fj.svg'
              ],
              [
                  'name'=>'Gambia',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/gm.svg'
              ],
              [
                  'name'=>'Georgia',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/ge.svg'
              ],
              [
                  'name'=>'Ghana',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/gh.svg'
              ],
              [
                  'name'=>'Greece',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/gr.svg'
              ],
              [
                  'name'=>'Grenada',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/gd.svg'
              ],
              [
                  'name'=>'Guatemala',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/gt.svg'
              ],
              [
                  'name'=>'Guinea Conakry',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/gn.svg'
              ],
              [
                  'name'=>'Guinea-Bissau',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/gw.svg'
              ],
              [
                  'name'=>'Guyana',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/gy.svg'
              ],
              [
                  'name'=>'Haiti',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/ht.svg'
              ],
              [
                  'name'=>'Honduras',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/hn.svg'
              ],
              [
                  'name'=>'India',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/in.svg'
              ],
              [
                  'name'=>'Indonesia',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/id.svg'
              ],
              [
                  'name'=>'Iraq',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/iq.svg'
              ],
              [
                  'name'=>'Jamaica',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/jm.svg'
              ],
              [
                  'name'=>'Jordan',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/jo.svg'
              ],
              [
                  'name'=>'Kazakhstan',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/kz.svg'
              ],
              [
                  'name'=>'Kenya',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/ke.svg'
              ],
              [
                  'name'=>'South Korea',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/kr.svg'
              ],
              [
                  'name'=>'Kuwait',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/kw.svg'
              ],
              [
                  'name'=>'Kyrgyzstan',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/kg.svg'
              ],
              [
                  'name'=>'Laos',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/la.svg'
              ],
              [
                  'name'=>'Lebanon',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/lb.svg'
              ],
              [
                  'name'=>'Liberia',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/lr.svg'
              ],
              [
                  'name'=>'Macedonia',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/mk.svg'
              ],
              [
                  'name'=>'Madagascar',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/mg.svg'
              ],
              [
                  'name'=>'Malawi',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/mw.svg'
              ],
              [
                  'name'=>'Malaysia',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/my.svg'
              ],
              [
                  'name'=>'Mali',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/ml.svg'
              ],
              [
                  'name'=>'Martinique',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/mq.svg'
              ],
              [
                  'name'=>'Mauritania',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/mr.svg'
              ],
              [
                  'name'=>'Mexico',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/mx.svg'
              ],
              [
                  'name'=>'Moldova',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/md.svg'
              ],
              [
                  'name'=>'Montserrat',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/ms.svg'
              ],
              [
                  'name'=>'Morocco',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/ma.svg'
              ],
              [
                  'name'=>'Mozambique',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/mz.svg'
              ],
              [
                  'name'=>'Myanmar',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/mm.svg'
              ],
              [
                  'name'=>'Namibia',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/na.svg'
              ],
              [
                  'name'=>'Nauru',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/nr.svg'
              ],
              [
                  'name'=>'Nepal',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/np.svg'
              ],
              [
                  'name'=>'Nicaragua',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/ni.svg'
              ],
              [
                  'name'=>'Niger',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/ne.svg'
              ],
              [
                  'name'=>'Nigeria',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/ng.svg'
              ],
              [
                  'name'=>'Oman',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/om.svg'
              ],
              [
                  'name'=>'Pakistan',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/pk.svg'
              ],
              [
                  'name'=>'Palestine',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/ps.svg'
              ],
              [
                  'name'=>'Panama',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/pa.svg'
              ],
              [
                  'name'=>'Papua New Guinea',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/pg.svg'
              ],
              [
                  'name'=>'Paraguay',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/py.svg'
              ],
              [
                  'name'=>'Peru',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/pe.svg'
              ],
              [
                  'name'=>'Philippines',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/ph.svg'
              ],
              [
                  'name'=>'Puerto Rico',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/pr.svg'
              ],
              [
                  'name'=>'Qatar',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/qa.svg'
              ],
              [
                  'name'=>'Romania',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/ro.svg'
              ],
              [
                  'name'=>'Russia',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/ru.svg'
              ],
              [
                  'name'=>'Rwanda',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/rw.svg'
              ],
              [
                  'name'=>'Saint Kitts And Nevis',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/kn.svg'
              ],
              [
                  'name'=>'Saint Lucia',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/lc.svg'
              ],
              [
                  'name'=>'Samoa',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/ws.svg'
              ],
              [
                  'name'=>'Senegal',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/sn.svg'
              ],
              [
                  'name'=>'Sierra Leone',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/sl.svg'
              ],
              [
                  'name'=>'Singapore',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/sg.svg'
              ],
              [
                  'name'=>'Somalia',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/so.svg'
              ],
              [
                  'name'=>'South Africa',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/za.svg'
              ],
              [
                  'name'=>'Sri Lanka',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/lk.svg'
              ],
              [
                  'name'=>'Suriname',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/sr.svg'
              ],
              [
                  'name'=>'Swaziland',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/sz.svg'
              ],
              [
                  'name'=>'Tajikistan',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/tj.svg'
              ],
              [
                  'name'=>'Tanzania',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/tz.svg'
              ],
              [
                  'name'=>'Thailand',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/th.svg'
              ],
              [
                  'name'=>'Togo',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/tg.svg'
              ],
              [
                  'name'=>'Tonga',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/to.svg'
              ],
              [
                  'name'=>'Trinidad and Tobago',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/tt.svg'
              ],
              [
                  'name'=>'Tunisia',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/tn.svg'
              ],
              [
                  'name'=>'Turkey',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/tr.svg'
              ],
              [
                  'name'=>'Turks And Caicos Islands',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/tc.svg'
              ],
              [
                  'name'=>'Uganda',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/ug.svg'
              ],
              [
                  'name'=>'Ukraine',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/ua.svg'
              ],
              [
                  'name'=>'Uruguay',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/uy.svg'
              ],
              [
                  'name'=>'Uzbekistan',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/uz.svg'
              ],
              [
                  'name'=>'Vanuatu',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/vu.svg'
              ],
              [
                  'name'=>'Venezuela',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/ve.svg'
              ],
              [
                  'name'=>'Vietnam',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/vn.svg'
              ],
              [
                  'name'=>'British Virgin Islands',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/vg.svg'
              ],
              [
                  'name'=>'Yemen',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/ye.svg'
              ],
              [
                  'name'=>'Zambia',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/zm.svg'
              ],
              [
                  'name'=>'Zimbabwe',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/zw.svg'
              ],
              [
                  'name'=>'Saint Vincent And The Grenadines',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/vc.svg'
              ],
              [
                  'name'=>'Netherlands Antilles',
                  'flag'=>'https://s3.amazonaws.com/rld-flags/ant.svg\n'
              ],
              [
                  'name'=>'UK',
                  'flag'=>NULL
              ],
              [
                  'name'=>'Switzerland',
                  'flag'=>NULL
              ],
              [
                  'name'=>'USA',
                  'flag'=>NULL
              ],
              [
                  'name'=>'UAE',
                  'flag'=>NULL
              ],
              [
                  'name'=>'Hong Kong',
                  'flag'=>NULL
              ],
              [
                  'name'=>'Czech Republic',
                  'flag'=>NULL
              ],
              [
                  'name'=>'Luxembourg',
                  'flag'=>NULL
              ],
              [
                  'name'=>'Denmark',
                  'flag'=>NULL
              ],
              [
                  'name'=>'Norway',
                  'flag'=>NULL
              ],
              [
                  'name'=>'Sweden',
                  'flag'=>NULL
              ],
              [
                  'name'=>'Hungary',
                  'flag'=>NULL
              ],
              [
                  'name'=>'Taiwan',
                  'flag'=>NULL
              ],
              [
                  'name'=>'Israel',
                  'flag'=>NULL
              ],
              [
                  'name'=>'Andorra',
                  'flag'=>NULL
              ],
              [
                  'name'=>'New Zealand',
                  'flag'=>NULL
              ]
          ]);
    }
}
